NAME: KITTIPair
data_path: /public2/KITTI
default_sequences: {
    'train': ["00", "01", "02", "04", "05", "06", "07", "08", "09", "10"],
    'val': ["02"],
    'test': ["00"]
}
contrast_mode: True # True for concate the query and database data, which is the whole image-point cloud pairs without query or database division
pre_save: false # save the whole positive and negative samples into pickle file to speed acceleration 

img_subdir: data_odometry_color
submap_subdir: Semantic_KITTI

image_size: [368, 1232] # raw image size [1440, 2880], [512, 1024] is preprocessing
proxy_image_size: [224, 224] # point cloud proxy image size, useless in this mode
img_channel: 3 # only rgb
point_cluod_fix_num: False # if to load from fixed number of point clouds
point_cloud_proxy: points # bev_image or range_image or none
points_num: 20480 #, 10240 # number of points loaded from bin file, note that the raw submap contains much more pts
point_limit: 30000 # maximum number of point in each bin file
point_channel: 3 # only xyz

nPos: 1 # number of positives
nNeg: 1 # 5 number of negatives
posDistThr: 20 # Euclidean distance
negDistThr: 40 # Euclidean distance

get_neighbor: False # if to construct neighbor pts at collate_fn
num_stages: 5
voxel_size: 0.3
search_radius: 1.275  # n * voxel_size,n = 2.5/3
precompute_data: True