NAME: KITTI360PanoramaTriplet
data_path: /public2/KITTI360
default_sequences: {
    'train': ["0", "2", "4", "5", "6", "7", "8", "9", "10", "18"],
    'val': ["0"],
    'test': ["0"]
}
contrast_mode: False # True for concate the query and database data, which is the whole image-point cloud pairs without query or database division
pre_save: false # save the whole positive and negative samples into pickle file to speed acceleration 

img_subdir: data_2d_pano_512_1024 # or data_2d_pano_384_1024
submap_subdir: data_3d_submap_raw

image_size: [512, 1024] # raw image size [1440, 2880], [512, 1024] is preprocessing
img_channel: 3 # only rgb

point_cloud_proxy: points # bev_image or range_image or none
points_num: 4096 #, 10240 # number of points loaded from bin file, note that the raw submap contains much more pts
point_channel: 3 # only xyz
nNeg: 5 # number of negatives

posDistThr: 20 # Euclidean distance
negDistThr: 40 # Euclidean distance

mining: False # switcher indicates whether to conduct data mining
cached_queries: 4000 # fixme
cached_negatives: 20000 # fixme

get_neighbor: False # if to construct neighbor pts at collate_fn